repos:
  - repo: local
    hooks:
      # Add unit test run here       

      - id: enforce-commit-prefix
        name: Enforcing Commit Message Prefix
        entry: scripts/enforce-commit-prefix.sh
        language: system
        pass_filenames: false
        stages: [commit-msg]

      # LINT-ONLY: fail if formatting is off
      - id: swiftformat-lint
        name: SwiftFormat (lint only)
        entry: swiftformat
        language: system
        types: [swift]
        pass_filenames: true
        args: ["--lint", "--quiet"]
        stages: [pre-commit]
 
